PACKAGE_NAME="oxpec-local"
PACKAGE_VERSION="1.0.0"
BUILT_MODULE_NAME[0]="oxpec"
DEST_MODULE_LOCATION[0]="/updates/dkms"
AUTOINSTALL="yes"
MAKE[0]="make KERNELRELEASE=${kernelver} KDIR=${kernel_source_dir}"
CLEAN="make clean"
